name: qa_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pip=23.3.1
  - pytorch=2.1.2
  - pytorch-cuda=12.1
  - numpy=1.26.3
  - tqdm=4.66.1
  - pip:
    - transformers==4.47.0
    - accelerate==0.26.0
    - huggingface-hub==0.25.0
    - sentencepiece==0.1.99
    - protobuf==4.25.1
    - bitsandbytes==0.45.1
    - safetensors==0.4.1
    - scipy==1.11.4
